all:
  children:

    swarm_manager:
      hosts:

        dev.diesel.net:

  vars:

    kiwi_host: grafana.dev.kiwi-labs.net
    diesel_host: grafana.dev.diesel.net

    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3
