kind: pipeline
type: docker
name: Build Grafana

clone:
  depth: 1

concurrency:
  limit: 1

steps:
  - name: deploy
    image: docker.nexus.diesel.net/drone-ansible:7.2.0
    environment:
      LDAP_ADMIN_PASSWORD:
        from_secret: ldap_admin_password
    settings:
      inventory: .ansible/inventories/prod.yaml
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password
trigger:
  branch:
    - development
    - stable
  event:
    - push

...
