kind: pipeline
type: docker
name: Deploy

clone:
  depth: 1

concurrency:
  limit: 1

steps:
  
  - name: deploy (${DRONE_BRANCH}) -> dev
    image: docker.nexus.diesel.net/drone-ansible:7.2.0
    environment:
      SMTP_USERNAME:
        from_secret: smtp_username
      SMTP_PASSWORD:
        from_secret: smtp_password
    settings:
      inventory: .ansible/inventories/dev.yaml
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password
    when:
      branch:
        - development

  - name: deploy (${DRONE_BRANCH}) -> prod
    image: docker.nexus.diesel.net/drone-ansible:7.2.0
    environment:
      SMTP_USERNAME:
        from_secret: smtp_username
      SMTP_PASSWORD:
        from_secret: smtp_password
    settings:
      inventory: .ansible/inventories/prod.yaml
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password
    when:
      branch:
        - stable


trigger:
  branch:
    - development
    - stable
  event:
    - push

...
