version: '3.8'
services:

  grafana:
    image: grafana/grafana-oss:8.5.2
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
      - /etc/localtime:/etc/localtime
      - {{ config_dir }}/grafana.ini:/etc/grafana/grafana.ini
      - {{ config_dir }}/ldap.toml:/etc/grafana/ldap.toml
      - {{ data_dir }}:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - traefik.http.routers.grafana.rule=Host(`{{ grafana_host }}`)
        - traefik.http.routers.grafana.tls.certresolver=step-ca
        - traefik.http.routers.grafana.service=grafana
    networks:
      - {{ traefik_network }}

networks:
  {{ traefik_network }}:
    external: true
    name: {{ traefik_network }}
