version: '3.8'
services:

  frontend:
    image: grafana/grafana-oss:10.2.3
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
      - /etc/localtime:/etc/localtime
      - {{ config_dir }}/files/grafana.ini:/etc/grafana/grafana.ini
      - {{ data_dir }}:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - HOSTNAME={{ kiwi_host }}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.{{ app_name }}-frontend.loadbalancer.server.port=3000

        - traefik.http.routers.diesel-{{ app_name }}.rule=Host(`{{ diesel_host }}`)
        - traefik.http.routers.diesel-{{ app_name }}.tls.certresolver=step-ca
        - traefik.http.routers.diesel-{{ app_name }}.service={{ app_name }}-frontend@docker

        - traefik.http.routers.kiwi-{{ app_name }}.rule=Host(`{{ kiwi_host }}`)
        - traefik.http.routers.kiwi-{{ app_name }}.tls.certresolver=cloudflare
        - traefik.http.routers.kiwi-{{ app_name }}.tls.domains[0].main={{ '.'.join( kiwi_host.split('.')[1:] ) }}
        - traefik.http.routers.kiwi-{{ app_name }}.tls.domains[0].sans=*.{{ '.'.join( kiwi_host.split('.')[1:] ) }}
        - traefik.http.routers.kiwi-{{ app_name }}.service={{ app_name }}-frontend@docker
    networks:
      - {{ traefik_network }}

networks:
  {{ traefik_network }}:
    external: true
    name: {{ traefik_network }}
