- hosts: swarm_manager
  roles:
    - application
    - traefik
  tasks:

    - include_role:
        name: application
        tasks_from: make_config_dir


    - include_role:
        name: application
        tasks_from: make_data_dir

    # notes on the file permissions: 
    # https://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v51-or-later

    - file:
        path: '{{ data_dir }}'
        owner: '472'
        group: '0'
        mode: u=rwx,g=rx
      become: yes

    - name: make config subdir
      file:
        path: '{{ config_dir }}/files'
        state: directory
        owner: '472'
        group: '0'
        mode: u=rwx,g=rx
      become: yes

    - name: 'render grafana.ini to {{ config_dir }}/files/grafana.ini'
      template:
        src: grafana.ini
        dest: '{{ config_dir }}/files/grafana.ini'
        owner: '472'
        group: '0'
        mode: u=rwx,g=rx
      become: yes


    - include_role:
        name: docker
        tasks_from: stack_deploy

    - include_role:
        name: docker
        tasks_from: service_update
      vars:
        options: --force
        docker_service: grafana
